version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Asuncion
    open-pull-requests-limit: 2
    groups:
      nextjs:
        patterns:
          - next
          - eslint-config-next
      react:
        patterns:
          - react
          - react-dom
          - "@types/react*"
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
